### ISSUE TITLE
Navbar todo-list

### ISSUE THREAD

**Issue by beautron7** [beautron7/Debate-Thing#1]
Todo list for Implementing navbar
- [ ] Implement a variable or getter function (`window.App.editor.currentSection`) to return the current path
- [ ] Create `window.App.editor.scrollToPath()` to scroll the view up or down
- [ ] Add breadcrumbs to navbar (Depending on feedback)
- [ ] Add collapsable nav spans to navbar
- [ ] Add right click menu to show heading levels
