### ISSUE TITLE
Editor todo list

### ISSUE THREAD

**Issue by beautron7** [beautron7/Debate-Thing#2]
- [x] Drag and drop card text
  - [x] Html5 backbone
  - [x] Function to actually retrieve the data from storage
- [ ] Drag and drop instances of cards (formatting)
- [ ] ~Drag and drop to reorder sections~
  - [ ] ~Don't interfere with nested cards~
  - [ ] ~Don't interfere with nested sections~
