### ISSUE TITLE
Card todo-list

### ISSUE THREAD

**Issue by beautron7** [beautron7/Debate-Thing#5]
- [ ] **F`or`m***atti*n~~g~~
  - [ ] Decide on the \`format\` to store **F`or`m***atti*n~~g~~
  - [ ] Implement select text & f1-f12 keys to format
  - [x] Implement select text & style menu to format
  - [ ] Auto-hide non highlighted text

**Comment by beautron7** [comment]
Moving to todo list
