### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by beautron7** [beautron7/Debate-Thing#9]
- [ ] Card stuff
    - [ ] Card Formatting
        - [ ] Buttons
        - [ ] Datastructure to save formatting
        - [ ] Code to make datastructure
    - [ ] Card Importing
        - [ ] Fix Modal for importing
    - [ ] Card Previewing
        - [ ] Loading text
        - [ ] Removing Unnessecary text from ram
    - [ ] Card Storage
        - [ ] Include Underlining / Highligting [Complete formatting first]
- [ ] Editor stuff
    - [ ] Convert state of editor to JSON
    - [ ] Save JSON
    - [ ] Nav-Pane
    - [ ] Associate file-extension with auto opening
    - [ ] Make sure all libraries work on linux / mac
